name: cart_service
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  shelf: ^1.3.0
  shelf_router: ^1.0.0

  core:
    git:
      url: https://github.com/kiryl-stalbou/microservices.git
      path: core
      ref: main

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
